version: '3'
services:
  backend:
    build:
      context: .
    restart: on-failure
    image: backend-fastapi
    container_name: backend-fastapi
    working_dir: /backend-fastapi
    volumes:
      - .:/backend-fastapi
    ports:
      - ${API_PORT}:8000
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: {}