"""Updated Ticket Model

Revision ID: 273d65d388af
Revises: 13769fc676f7
Create Date: 2024-04-20 04:51:57.525966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273d65d388af'
down_revision: Union[str, None] = '13769fc676f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'closed_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'closed_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
